### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by DPontes** [llSourcell/word_vectors_game_of_thrones-LIVE#2]
Hi,

it seems that the requirements.txt file is missing...

**Comment by malhotraa** [comment]
Hi @llSourcell , can you add requirements.txt? Thanks.

**Comment by zzzzddddgtuwup** [comment]
You could find requirements here. https://github.com/YuriyGuts/thrones2vec

Note: some packages in requirements.txt may be olded than your existing package version. If you run "pip install -r pip-requirements.txt", it will uninstalled your existing package and install old ones.
